coarse_mapping = {
    "Caribbean dance (Abakua, Beguine, Bellair, Bongo, Brukin's, Caribbean Quadrills, Dinki Mini, Gere, G": 'dancing',
    'aerobic, general': 'fitness_exercise',
    'aerobic, step': 'fitness_exercise',
    'backpacking': 'walking',
    'badminton, social singles and doubles, general': 'sports_ball',
    'ballet, modern, or jazz': 'dancing',
    'ballroom': 'dancing',
    'basketball': 'sports_ball',
    'basketball, game (Taylor Code 490)': 'sports_ball',
    'bicycling, mountain': 'cycling',
    'bicycling, racing and road': 'cycling',
    'bicycling, stationary': 'cycling',
    'broomball': 'sports_ball',
    'calisthenics': 'fitness_exercise',
    'canoeing, kayaking, rowing, competitive': 'sports_other',
    'carpentry, finishing or refinishing cabinets or furniture': 'household',
    'carpentry, general': 'household',
    'carpentry, sawing hardwood': 'household',
    'child care': 'other',
    'children_s games, adults playing (e.g., hopscotch, 4-square, dodgeball, playground apparatus, t-ball': 'other',
    'chopping wood': 'fitness_exercise',
    'circuit training': 'fitness_exercise',
    'coaching': 'other',
    'cook, chef': 'household',
    'cooking or food preparation': 'household',
    'ethnic or cultural dancing (e.g., Greek, Middle Eastern, hula, salsa, merengue, bamba y plena, flame': 'dancing',
    'farming, cultivating field': 'household',
    'farming, rice, planting, grain milling activities': 'household',
    'fencing': 'sports_other',
    'fire fighter': 'other',
    'fishing from river bank': 'household',
    'fishing, commercial': 'household',
    'fishing, general': 'household',
    'football, touch, flag': 'sports_ball',
    'forestry': 'household',
    'frisbee': 'sports_ball',
    'golf': 'sports_other',
    'hairstylist (e.g., plaiting hair, manicure, make-up artist)': 'household',
    'health club exerceise classes': 'fitness_exercise',
    'horse grooming, feeding, cleaning, harnessing and unharnessing': 'sports_other',
    'horseback riding': 'sports_other',
    'lacrosse': 'sports_ball',
    'marching band': 'music_playing',
    'martial arts, different types': 'other',
    'massage therapist, standing': 'standing',
    'paddleball': 'sports_ball',
    'planting, potting, transplanting seedlings or plants, light effort': 'household',
    'playing with animals': 'other',
    'playing with children': 'other',
    'racquetball': 'sports_ball',
    'resistance training': 'fitness_exercise',
    'rock climbing': 'sports_other',
    'rollerblading': 'sports_other',
    'rope skipping, general': 'jumping',
    'rowing, stationary': 'sports_other',
    'rugby, touch, non-competitive': 'sports_ball',
    'running': 'running',
    'running, marathon': 'running',
    'serving food and drinks': 'other',
    'sitting quietly': 'sitting',
    'sitting, talking in person, on the phone, computer, or text messaging, light effort': 'sitting',
    'skateboarding': 'sports_other',
    'skating, ice': 'sports_other',
    'skiing, cross-country, biathlon, skating technique': 'sports_other',
    'skiing, downhill': 'sports_other',
    'soccer': 'sports_ball',
    'softball, general': 'sports_ball',
    'squash': 'sports_ball',
    'standing quietly, standing in a line': 'standing',
    'standing, arts and crafts, sand painting, carving, weaving': 'standing',
    'standing, doing work': 'standing',
    'standing, miscellaneous': 'standing',
    'standing, talking in church': 'standing',
    'standing, talking in person': 'standing',
    'swimming, lake, ocean, river (Taylor Codes 280, 295)': 'swimming',
    'tai chi, qi gong, general': 'fitness_exercise',
    'tailoring': 'household',
    'therapeutic exercise ball, Fitball exercise': 'fitness_exercise',
    'touringtravelingvacation involving riding in a vehicle': 'other',
    'track and field': 'sports_other',
    'trimming shrubs or trees': 'fitness_exercise',
    'video exercise workouts, TV conditioning programs': 'fitness_exercise',
    'volleyball, indoor': 'sports_ball',
    'walking, for exerceise, with ski poles': 'walking',
    'walking, general': 'walking',
    'walkrun play with children, moderate, only active periods': 'walking',
    'water walking': 'walking',
    'yoga, Power': 'fitness_exercise',
}
